version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 54321:5432
    volumes:
      - ~/apps/pierre-portfolio:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=pierre
      - POSTGRES_DB=pierre